# Generated by Django 2.2.1 on 2019-05-08 21:36

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_kin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kin',
            name='type',
            field=django_mysql.models.EnumField(choices=[('wedding', 'wedding'), ('sunshineloan', 'sunshineloan')], null=True),
        ),
    ]
