# Generated by Django 2.2.1 on 2019-05-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20190508_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kin',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
