# Generated by Django 2.2.1 on 2019-05-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20190508_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='role',
        ),
        migrations.AddField(
            model_name='reply',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
